import type { Express, Request, Response } from "express";
import { storage } from "../storage";
import { apiResponse, logAction } from "./_helpers";

export function registerPermissionRoutes(app: Express) {
  app.get("/api/admin/permissions", async (req: Request, res: Response) => {
    try {
      const permissions = await storage.getAllPermissions();
      res.json(permissions);
    } catch (error) {
      res.json([]);
    }
  });

  app.get(
    "/api/admin/role-permissions",
    async (req: Request, res: Response) => {
      try {
        const rolePermissions = await storage.getAllRolePermissions();
        res.json(rolePermissions);
      } catch (error) {
        res.json([]);
      }
    },
  );

  app.post(
    "/api/admin/role-permissions",
    async (req: Request, res: Response) => {
      try {
        const { roleId, permissionId, adminId } = req.body;

        const assignment = await storage.assignRolePermission({
          roleId,
          permissionId,
        });

        await logAction(
          adminId || "admin",
          "Permission Assigned",
          "role_permissions",
          assignment.id,
          null,
          {
            roleId,
            permissionId,
          },
        );

        res.json(apiResponse(true, assignment));
      } catch (error) {
        res.json(apiResponse(false, null, "Failed to assign permission"));
      }
    },
  );

  app.delete(
    "/api/admin/role-permissions",
    async (req: Request, res: Response) => {
      try {
        const { roleId, permissionId, adminId } = req.body;

        await storage.removeRolePermission(roleId, permissionId);

        await logAction(
          adminId || "admin",
          "Permission Removed",
          "role_permissions",
          null,
          { roleId, permissionId },
          null,
        );

        res.json(apiResponse(true, null));
      } catch (error) {
        res.json(apiResponse(false, null, "Failed to remove permission"));
      }
    },
  );

  app.delete(
    "/api/admin/role-permissions/:roleId/:permissionId",
    async (req: Request, res: Response) => {
      try {
        const { roleId, permissionId } = req.params;

        await storage.removeRolePermission(roleId, permissionId);

        await logAction(
          "admin",
          "Permission Removed",
          "role_permissions",
          null,
          { roleId, permissionId },
          null,
        );

        res.json(apiResponse(true, null));
      } catch (error) {
        res.json(apiResponse(false, null, "Failed to remove permission"));
      }
    },
  );

  app.post(
    "/api/admin/permissions/seed",
    async (req: Request, res: Response) => {
      try {
        const hierarchicalPermissions = [
          {
            id: "users",
            code: "users",
            name: "User Management",
            nameEn: "User Management",
            nameAr: "إدارة المستخدمين",
            descriptionEn: "User management operations",
            descriptionAr: "عمليات إدارة المستخدمين",
            module: "users",
            action: "manage",
            parentId: null,
          },
          {
            id: "users.view",
            code: "users.view",
            name: "View Users",
            nameEn: "View Users",
            nameAr: "عرض المستخدمين",
            descriptionEn: "View user list and details",
            descriptionAr: "عرض قائمة المستخدمين وتفاصيلهم",
            module: "users",
            action: "view",
            parentId: "users",
          },
          {
            id: "users.create",
            code: "users.create",
            name: "Create User",
            nameEn: "Create User",
            nameAr: "إنشاء مستخدم",
            descriptionEn: "Create new user accounts",
            descriptionAr: "إنشاء حسابات مستخدمين جديدة",
            module: "users",
            action: "create",
            parentId: "users",
          },
          {
            id: "users.edit",
            code: "users.edit",
            name: "Edit User",
            nameEn: "Edit User",
            nameAr: "تعديل المستخدم",
            descriptionEn: "Modify user information",
            descriptionAr: "تعديل معلومات المستخدم",
            module: "users",
            action: "edit",
            parentId: "users",
          },
          {
            id: "users.edit.profile",
            code: "users.edit.profile",
            name: "Edit Profile",
            nameEn: "Edit Profile",
            nameAr: "تعديل الملف الشخصي",
            descriptionEn: "Edit user profile details",
            descriptionAr: "تعديل تفاصيل الملف الشخصي",
            module: "users",
            action: "edit",
            parentId: "users.edit",
          },
          {
            id: "users.edit.status",
            code: "users.edit.status",
            name: "Change Status",
            nameEn: "Change Status",
            nameAr: "تغيير الحالة",
            descriptionEn: "Change user account status",
            descriptionAr: "تغيير حالة حساب المستخدم",
            module: "users",
            action: "edit",
            parentId: "users.edit",
          },
          {
            id: "users.delete",
            code: "users.delete",
            name: "Delete User",
            nameEn: "Delete User",
            nameAr: "حذف المستخدم",
            descriptionEn: "Remove user accounts",
            descriptionAr: "حذف حسابات المستخدمين",
            module: "users",
            action: "delete",
            parentId: "users",
          },
          {
            id: "roles",
            code: "roles",
            name: "Role Management",
            nameEn: "Role Management",
            nameAr: "إدارة الأدوار",
            descriptionEn: "Role management operations",
            descriptionAr: "عمليات إدارة الأدوار",
            module: "roles",
            action: "manage",
            parentId: null,
          },
          {
            id: "roles.view",
            code: "roles.view",
            name: "View Roles",
            nameEn: "View Roles",
            nameAr: "عرض الأدوار",
            descriptionEn: "View role list and details",
            descriptionAr: "عرض قائمة الأدوار وتفاصيلها",
            module: "roles",
            action: "view",
            parentId: "roles",
          },
          {
            id: "roles.create",
            code: "roles.create",
            name: "Create Role",
            nameEn: "Create Role",
            nameAr: "إنشاء دور",
            descriptionEn: "Create new roles",
            descriptionAr: "إنشاء أدوار جديدة",
            module: "roles",
            action: "create",
            parentId: "roles",
          },
          {
            id: "roles.edit",
            code: "roles.edit",
            name: "Edit Role",
            nameEn: "Edit Role",
            nameAr: "تعديل الدور",
            descriptionEn: "Modify role settings",
            descriptionAr: "تعديل إعدادات الدور",
            module: "roles",
            action: "edit",
            parentId: "roles",
          },
          {
            id: "roles.edit.permissions",
            code: "roles.edit.permissions",
            name: "Manage Permissions",
            nameEn: "Manage Permissions",
            nameAr: "إدارة الصلاحيات",
            descriptionEn: "Assign permissions to roles",
            descriptionAr: "تعيين الصلاحيات للأدوار",
            module: "roles",
            action: "edit",
            parentId: "roles.edit",
          },
          {
            id: "roles.edit.users",
            code: "roles.edit.users",
            name: "Assign Users",
            nameEn: "Assign Users",
            nameAr: "تعيين المستخدمين",
            descriptionEn: "Assign users to roles",
            descriptionAr: "تعيين المستخدمين للأدوار",
            module: "roles",
            action: "edit",
            parentId: "roles.edit",
          },
          {
            id: "roles.delete",
            code: "roles.delete",
            name: "Delete Role",
            nameEn: "Delete Role",
            nameAr: "حذف الدور",
            descriptionEn: "Remove roles",
            descriptionAr: "حذف الأدوار",
            module: "roles",
            action: "delete",
            parentId: "roles",
          },
          {
            id: "draws",
            code: "draws",
            name: "Draw Management",
            nameEn: "Draw Management",
            nameAr: "إدارة السحوبات",
            descriptionEn: "Lottery draw operations",
            descriptionAr: "عمليات السحب",
            module: "draws",
            action: "manage",
            parentId: null,
          },
          {
            id: "draws.view",
            code: "draws.view",
            name: "View Draws",
            nameEn: "View Draws",
            nameAr: "عرض السحوبات",
            descriptionEn: "View draw list and details",
            descriptionAr: "عرض قائمة السحوبات وتفاصيلها",
            module: "draws",
            action: "view",
            parentId: "draws",
          },
          {
            id: "draws.create",
            code: "draws.create",
            name: "Create Draw",
            nameEn: "Create Draw",
            nameAr: "إنشاء سحب",
            descriptionEn: "Create new lottery draws",
            descriptionAr: "إنشاء سحوبات جديدة",
            module: "draws",
            action: "create",
            parentId: "draws",
          },
          {
            id: "draws.edit",
            code: "draws.edit",
            name: "Edit Draw",
            nameEn: "Edit Draw",
            nameAr: "تعديل السحب",
            descriptionEn: "Modify draw settings",
            descriptionAr: "تعديل إعدادات السحب",
            module: "draws",
            action: "edit",
            parentId: "draws",
          },
          {
            id: "draws.edit.prizes",
            code: "draws.edit.prizes",
            name: "Manage Prizes",
            nameEn: "Manage Prizes",
            nameAr: "إدارة الجوائز",
            descriptionEn: "Configure draw prizes",
            descriptionAr: "تكوين جوائز السحب",
            module: "draws",
            action: "edit",
            parentId: "draws.edit",
          },
          {
            id: "draws.edit.schedule",
            code: "draws.edit.schedule",
            name: "Schedule Draw",
            nameEn: "Schedule Draw",
            nameAr: "جدولة السحب",
            descriptionEn: "Set draw date and time",
            descriptionAr: "تحديد تاريخ ووقت السحب",
            module: "draws",
            action: "edit",
            parentId: "draws.edit",
          },
          {
            id: "draws.execute",
            code: "draws.execute",
            name: "Execute Draw",
            nameEn: "Execute Draw",
            nameAr: "تنفيذ السحب",
            descriptionEn: "Run lottery draw",
            descriptionAr: "تشغيل السحب",
            module: "draws",
            action: "execute",
            parentId: "draws",
          },
          {
            id: "draws.delete",
            code: "draws.delete",
            name: "Delete Draw",
            nameEn: "Delete Draw",
            nameAr: "حذف السحب",
            descriptionEn: "Remove draws",
            descriptionAr: "حذف السحوبات",
            module: "draws",
            action: "delete",
            parentId: "draws",
          },
          {
            id: "tickets",
            code: "tickets",
            name: "Ticket Management",
            nameEn: "Ticket Management",
            nameAr: "إدارة التذاكر",
            descriptionEn: "Lottery ticket operations",
            descriptionAr: "عمليات التذاكر",
            module: "tickets",
            action: "manage",
            parentId: null,
          },
          {
            id: "tickets.view",
            code: "tickets.view",
            name: "View Tickets",
            nameEn: "View Tickets",
            nameAr: "عرض التذاكر",
            descriptionEn: "View ticket list and details",
            descriptionAr: "عرض قائمة التذاكر وتفاصيلها",
            module: "tickets",
            action: "view",
            parentId: "tickets",
          },
          {
            id: "tickets.view.all",
            code: "tickets.view.all",
            name: "View All Tickets",
            nameEn: "View All Tickets",
            nameAr: "عرض جميع التذاكر",
            descriptionEn: "View all user tickets",
            descriptionAr: "عرض جميع تذاكر المستخدمين",
            module: "tickets",
            action: "view",
            parentId: "tickets.view",
          },
          {
            id: "tickets.view.own",
            code: "tickets.view.own",
            name: "View Own Tickets",
            nameEn: "View Own Tickets",
            nameAr: "عرض تذاكري",
            descriptionEn: "View own tickets only",
            descriptionAr: "عرض التذاكر الخاصة فقط",
            module: "tickets",
            action: "view",
            parentId: "tickets.view",
          },
          {
            id: "tickets.purchase",
            code: "tickets.purchase",
            name: "Purchase Tickets",
            nameEn: "Purchase Tickets",
            nameAr: "شراء التذاكر",
            descriptionEn: "Buy lottery tickets",
            descriptionAr: "شراء تذاكر اليانصيب",
            module: "tickets",
            action: "create",
            parentId: "tickets",
          },
          {
            id: "tickets.refund",
            code: "tickets.refund",
            name: "Refund Tickets",
            nameEn: "Refund Tickets",
            nameAr: "استرداد التذاكر",
            descriptionEn: "Process ticket refunds",
            descriptionAr: "معالجة استرداد التذاكر",
            module: "tickets",
            action: "refund",
            parentId: "tickets",
          },
          {
            id: "payments",
            code: "payments",
            name: "Payment Management",
            nameEn: "Payment Management",
            nameAr: "إدارة المدفوعات",
            descriptionEn: "Payment operations",
            descriptionAr: "عمليات الدفع",
            module: "payments",
            action: "manage",
            parentId: null,
          },
          {
            id: "payments.view",
            code: "payments.view",
            name: "View Payments",
            nameEn: "View Payments",
            nameAr: "عرض المدفوعات",
            descriptionEn: "View payment transactions",
            descriptionAr: "عرض معاملات الدفع",
            module: "payments",
            action: "view",
            parentId: "payments",
          },
          {
            id: "payments.process",
            code: "payments.process",
            name: "Process Payments",
            nameEn: "Process Payments",
            nameAr: "معالجة المدفوعات",
            descriptionEn: "Process payment transactions",
            descriptionAr: "معالجة معاملات الدفع",
            module: "payments",
            action: "process",
            parentId: "payments",
          },
          {
            id: "payments.refund",
            code: "payments.refund",
            name: "Process Refunds",
            nameEn: "Process Refunds",
            nameAr: "معالجة الاستردادات",
            descriptionEn: "Process payment refunds",
            descriptionAr: "معالجة استردادات الدفع",
            module: "payments",
            action: "refund",
            parentId: "payments",
          },
          {
            id: "wallet",
            code: "wallet",
            name: "Wallet Management",
            nameEn: "Wallet Management",
            nameAr: "إدارة المحفظة",
            descriptionEn: "Wallet operations",
            descriptionAr: "عمليات المحفظة",
            module: "wallet",
            action: "manage",
            parentId: null,
          },
          {
            id: "wallet.view",
            code: "wallet.view",
            name: "View Wallet",
            nameEn: "View Wallet",
            nameAr: "عرض المحفظة",
            descriptionEn: "View wallet balance and history",
            descriptionAr: "عرض رصيد المحفظة والسجل",
            module: "wallet",
            action: "view",
            parentId: "wallet",
          },
          {
            id: "wallet.deposit",
            code: "wallet.deposit",
            name: "Deposit Funds",
            nameEn: "Deposit Funds",
            nameAr: "إيداع الأموال",
            descriptionEn: "Add funds to wallet",
            descriptionAr: "إضافة أموال للمحفظة",
            module: "wallet",
            action: "deposit",
            parentId: "wallet",
          },
          {
            id: "wallet.withdraw",
            code: "wallet.withdraw",
            name: "Withdraw Funds",
            nameEn: "Withdraw Funds",
            nameAr: "سحب الأموال",
            descriptionEn: "Withdraw funds from wallet",
            descriptionAr: "سحب أموال من المحفظة",
            module: "wallet",
            action: "withdraw",
            parentId: "wallet",
          },
          {
            id: "audit",
            code: "audit",
            name: "Audit Logs",
            nameEn: "Audit Logs",
            nameAr: "سجلات التدقيق",
            descriptionEn: "Audit log operations",
            descriptionAr: "عمليات سجلات التدقيق",
            module: "audit",
            action: "manage",
            parentId: null,
          },
          {
            id: "audit.view",
            code: "audit.view",
            name: "View Audit Logs",
            nameEn: "View Audit Logs",
            nameAr: "عرض سجلات التدقيق",
            descriptionEn: "View system audit logs",
            descriptionAr: "عرض سجلات تدقيق النظام",
            module: "audit",
            action: "view",
            parentId: "audit",
          },
          {
            id: "audit.export",
            code: "audit.export",
            name: "Export Logs",
            nameEn: "Export Logs",
            nameAr: "تصدير السجلات",
            descriptionEn: "Export audit logs",
            descriptionAr: "تصدير سجلات التدقيق",
            module: "audit",
            action: "export",
            parentId: "audit",
          },
          {
            id: "reports",
            code: "reports",
            name: "Reports & Analytics",
            nameEn: "Reports & Analytics",
            nameAr: "التقارير والتحليلات",
            descriptionEn: "Reporting operations",
            descriptionAr: "عمليات التقارير",
            module: "reports",
            action: "manage",
            parentId: null,
          },
          {
            id: "reports.view",
            code: "reports.view",
            name: "View Reports",
            nameEn: "View Reports",
            nameAr: "عرض التقارير",
            descriptionEn: "View system reports",
            descriptionAr: "عرض تقارير النظام",
            module: "reports",
            action: "view",
            parentId: "reports",
          },
          {
            id: "reports.view.sales",
            code: "reports.view.sales",
            name: "Sales Reports",
            nameEn: "Sales Reports",
            nameAr: "تقارير المبيعات",
            descriptionEn: "View sales reports",
            descriptionAr: "عرض تقارير المبيعات",
            module: "reports",
            action: "view",
            parentId: "reports.view",
          },
          {
            id: "reports.view.financial",
            code: "reports.view.financial",
            name: "Financial Reports",
            nameEn: "Financial Reports",
            nameAr: "التقارير المالية",
            descriptionEn: "View financial reports",
            descriptionAr: "عرض التقارير المالية",
            module: "reports",
            action: "view",
            parentId: "reports.view",
          },
          {
            id: "reports.view.users",
            code: "reports.view.users",
            name: "User Reports",
            nameEn: "User Reports",
            nameAr: "تقارير المستخدمين",
            descriptionEn: "View user reports",
            descriptionAr: "عرض تقارير المستخدمين",
            module: "reports",
            action: "view",
            parentId: "reports.view",
          },
          {
            id: "reports.export",
            code: "reports.export",
            name: "Export Reports",
            nameEn: "Export Reports",
            nameAr: "تصدير التقارير",
            descriptionEn: "Export reports to file",
            descriptionAr: "تصدير التقارير لملف",
            module: "reports",
            action: "export",
            parentId: "reports",
          },
          {
            id: "settings",
            code: "settings",
            name: "Settings",
            nameEn: "Settings",
            nameAr: "الإعدادات",
            descriptionEn: "System configuration",
            descriptionAr: "تكوين النظام",
            module: "settings",
            action: "manage",
            parentId: null,
          },
          {
            id: "settings.system",
            code: "settings.system",
            name: "System Settings",
            nameEn: "System Settings",
            nameAr: "إعدادات النظام",
            descriptionEn: "System-level settings",
            descriptionAr: "إعدادات مستوى النظام",
            module: "settings",
            action: "manage",
            parentId: "settings",
          },
          {
            id: "settings.system.view",
            code: "settings.system.view",
            name: "View System Settings",
            nameEn: "View System Settings",
            nameAr: "عرض إعدادات النظام",
            descriptionEn: "View system settings",
            descriptionAr: "عرض إعدادات النظام",
            module: "settings",
            action: "view",
            parentId: "settings.system",
          },
          {
            id: "settings.system.edit",
            code: "settings.system.edit",
            name: "Edit System Settings",
            nameEn: "Edit System Settings",
            nameAr: "تعديل إعدادات النظام",
            descriptionEn: "Edit system settings",
            descriptionAr: "تعديل إعدادات النظام",
            module: "settings",
            action: "edit",
            parentId: "settings.system",
          },
          {
            id: "settings.system.security",
            code: "settings.system.security",
            name: "Security Settings",
            nameEn: "Security Settings",
            nameAr: "إعدادات الأمان",
            descriptionEn: "Edit security settings",
            descriptionAr: "تعديل إعدادات الأمان",
            module: "settings",
            action: "edit",
            parentId: "settings.system",
          },
          {
            id: "settings.custom",
            code: "settings.custom",
            name: "Custom Settings",
            nameEn: "Custom Settings",
            nameAr: "الإعدادات المخصصة",
            descriptionEn: "Custom configuration",
            descriptionAr: "التكوين المخصص",
            module: "settings",
            action: "manage",
            parentId: "settings",
          },
          {
            id: "settings.custom.view",
            code: "settings.custom.view",
            name: "View Custom Settings",
            nameEn: "View Custom Settings",
            nameAr: "عرض الإعدادات المخصصة",
            descriptionEn: "View custom settings",
            descriptionAr: "عرض الإعدادات المخصصة",
            module: "settings",
            action: "view",
            parentId: "settings.custom",
          },
          {
            id: "settings.custom.edit",
            code: "settings.custom.edit",
            name: "Edit Custom Settings",
            nameEn: "Edit Custom Settings",
            nameAr: "تعديل الإعدادات المخصصة",
            descriptionEn: "Edit custom settings",
            descriptionAr: "تعديل الإعدادات المخصصة",
            module: "settings",
            action: "edit",
            parentId: "settings.custom",
          },
          {
            id: "settings.custom.payment",
            code: "settings.custom.payment",
            name: "Payment Settings",
            nameEn: "Payment Settings",
            nameAr: "إعدادات الدفع",
            descriptionEn: "Edit payment settings",
            descriptionAr: "تعديل إعدادات الدفع",
            module: "settings",
            action: "edit",
            parentId: "settings.custom",
          },
          {
            id: "settings.preferences",
            code: "settings.preferences",
            name: "Preferences",
            nameEn: "Preferences",
            nameAr: "التفضيلات",
            descriptionEn: "User preferences",
            descriptionAr: "تفضيلات المستخدم",
            module: "settings",
            action: "manage",
            parentId: "settings",
          },
          {
            id: "settings.preferences.view",
            code: "settings.preferences.view",
            name: "View Preferences",
            nameEn: "View Preferences",
            nameAr: "عرض التفضيلات",
            descriptionEn: "View preferences",
            descriptionAr: "عرض التفضيلات",
            module: "settings",
            action: "view",
            parentId: "settings.preferences",
          },
          {
            id: "settings.preferences.edit",
            code: "settings.preferences.edit",
            name: "Edit Preferences",
            nameEn: "Edit Preferences",
            nameAr: "تعديل التفضيلات",
            descriptionEn: "Edit preferences",
            descriptionAr: "تعديل التفضيلات",
            module: "settings",
            action: "edit",
            parentId: "settings.preferences",
          },
          {
            id: "settings.preferences.notifications",
            code: "settings.preferences.notifications",
            name: "Notification Settings",
            nameEn: "Notification Settings",
            nameAr: "إعدادات الإشعارات",
            descriptionEn: "Edit notification settings",
            descriptionAr: "تعديل إعدادات الإشعارات",
            module: "settings",
            action: "edit",
            parentId: "settings.preferences",
          },
          {
            id: "dashboard",
            code: "dashboard",
            name: "Dashboard",
            nameEn: "Dashboard",
            nameAr: "لوحة التحكم",
            descriptionEn: "Dashboard access",
            descriptionAr: "الوصول للوحة التحكم",
            module: "dashboard",
            action: "view",
            parentId: null,
          },
          {
            id: "dashboard.view",
            code: "dashboard.view",
            name: "View Dashboard",
            nameEn: "View Dashboard",
            nameAr: "عرض لوحة التحكم",
            descriptionEn: "View dashboard",
            descriptionAr: "عرض لوحة التحكم",
            module: "dashboard",
            action: "view",
            parentId: "dashboard",
          },
          {
            id: "dashboard.stats",
            code: "dashboard.stats",
            name: "View Statistics",
            nameEn: "View Statistics",
            nameAr: "عرض الإحصائيات",
            descriptionEn: "View system statistics",
            descriptionAr: "عرض إحصائيات النظام",
            module: "dashboard",
            action: "view",
            parentId: "dashboard",
          },
        ];

        await storage.clearAllPermissions();

        for (const perm of hierarchicalPermissions) {
          await storage.createPermission(perm);
        }

        res.json(
          apiResponse(
            true,
            { count: hierarchicalPermissions.length },
            "Permissions seeded successfully",
          ),
        );
      } catch (error) {
        console.error("Failed to seed permissions:", error);
        res.json(apiResponse(false, null, "Failed to seed permissions"));
      }
    },
  );
}
